Add Historical orthophotomap to Open external
FreemapSlovakia/freemap-v3-react pull request #554
Opened 2021-01-03 20:12 UTC by seg-on

Try open external Historical orthophotomap.  Zoom is now fixed on 1:2500.

2021-01-03 20:32 UTC, zdila requested changes
neviem ci take mje dobre mat na freemape. je to podla mna taka zaujimavost ktoru si pozrie par ludi raz a uz nikdy viac. a ak sa k tomu niekto chce vratit tak moze ist rovno na ten poral...

2021-01-03 20:32 UTC, zdila commented on src/translations/sk.tsx
> +    of1950: 'Historick� ortofotomapa',
nejaky divny encoding

2021-01-03 20:32 UTC, zdila commented on src/translations/cs.tsx
> +    of1950: 'Historick� ortofotomapa',
nejaky divny encoding

2021-01-03 20:32 UTC, zdila commented on src/components/OpenInExternalAppMenuItems.tsx
> +}
tento kod isto neprejde tslintom. minimalne to `var` a formatovanie.

2021-01-03 21:47 UTC, seg-on commented
Pokus bol :D
Otvorenie na rovnakom mieste je prakticky jediný prínos nakoľko sa v tých snímkach horšie orientuje.

2021-01-04 08:56 UTC, zdila commented
mozno lepsie pred implementaciou prediskutovat na slacku alebo maling liste :-)

2021-01-04 17:06 UTC, seg-on commented
Mal som pocit že sa ti moc nechce písať cez slack :D
Nabudúce napíšem.

2021-01-04 17:06 UTC, closed without merging