Added option to change the marker for POIs
FreemapSlovakia/freemap-v3-react pull request #724
Opened 2023-11-02 09:39 UTC by robo311

Zmena markeru na mape pre objekty POI sa nachádza pod názvom "Objekty (POI)". Markery su prednastavené - default, ring, rectangle.

2023-11-02 14:01 UTC, zdila requested changes
Rozbilo to layout panelu: 
![image](https://github.com/FreemapSlovakia/freemap-v3-react/assets/636095/5637858a-88ab-467d-95a1-832c3394aee8)

Ring icon ma nejaký hrubý okraj a je po stranách orezaný: 
![image](https://github.com/FreemapSlovakia/freemap-v3-react/assets/636095/70cf0496-186a-4210-b0ac-631286083962)

Naviac si myslím, že to nastavenie ma byť globálne a zapamätané pre použivateľa (ako je napr. zvolený jazyk). Ale treba navrhnut kde, kedze "settings" uz nemame (kedysi bolo).

2023-11-02 18:19 UTC, robo311 commented on src/components/SearchResults.tsx
> +  /* const selectedIconValue = useSelector((state: RootState) => state.main.selectedIcon) */
Odstránené.

2023-11-02 18:20 UTC, robo311 commented on src/components/ToolMenu.tsx
> +                <option value="default">Default Icon</option>
Neviem akým spôsobom sa získavajú preklady alebo akým spôsobom sú pridávané. Na prekladoch som ešte nerobil.

2023-11-02 18:21 UTC, robo311 commented on src/components/ObjectsResult.tsx
> +/* import { RichMarker } from 'fm3/components/RichMarker'; */
Odstránené, omylom zanechané

2023-11-02 18:21 UTC, robo311 commented on src/components/ToolMenu.tsx
> +
Odstránené.

2023-11-02 18:22 UTC, robo311 commented on src/components/ObjectMarker.tsx
> +export function ObjectMarker({
Odstránil som celý súbor a presunul som to do RichMarkeru.

2023-11-02 18:26 UTC, robo311 commented
> Rozbilo to layout panelu: ![image](https://user-images.githubusercontent.com/636095/280009835-5637858a-88ab-467d-95a1-832c3394aee8.png)

Už by to malo byť opravené.

> Ring icon ma nejaký hrubý okraj a je po stranách orezaný: ![image](https://user-images.githubusercontent.com/636095/280010150-70cf0496-186a-4210-b0ac-631286083962.png)

Toto som si ani nevšimol, až ked som si to priblížil tak vtedy. Takisto už by to malo byť opravené.

> Naviac si myslím, že to nastavenie ma byť globálne a zapamätané pre použivateľa (ako je napr. zvolený jazyk). Ale treba navrhnut kde, kedze "settings" uz nemame (kedysi bolo).

Prišlo mi to vhodné umiestniť túto fíčuru takto. Príde mi to zbytočné dávať niekde inde ak sa tým menia len objekty. Čo sa týka zapamätatelnosti, tak všimol som si, že veci ako výber jazyku, či iné záležitosti na mape sú riešené cez localStorage (aspoň sa tak ukladajú), no v kóde som to nenašiel.

2023-11-05 11:46 UTC, zdila requested changes
- to menu vyzerá lepšie, ale inšpiruj sa prosím dropdownami na iných miestach - napríklad v toolbare changesetov (https://github.com/FreemapSlovakia/freemap-v3-react/blob/develop/src/components/ChangesetsMenu.tsx#L34)
- iconAnchor tých nových ikon nesedí = je na spodku ikony, očakával by som ho v strede ikony
- ring icon má širší okraj ako rectangle icon, spravil by som ho rovnako tenký
- až tak nevidím význam mať obe ring aj rectangle. Hlavný prínos má byť aby to bolo prehľadnejšie pri prehustených POI. Za mňa by stačilo mať len "ring icon" a možno ešte menší. Ale toto konkrétne teraz nevyžadujem, len je to môj názor.

2023-11-05 11:53 UTC, zdila commented on src/components/ToolMenu.tsx
> +                <option value="default">Default Icon</option>
preklad sa robí takto:
- do `src/translations/messagesInterface.ts` pridáš nový "key" na vhodné miesto
- pridáš preklady do `src/translations/sk.tsx` (okrem `sk` aj `cs`, `it`, `hu`, `en`). Pomôže google translate ale pridaj poznámku `// TODO translated with google translate` aby to potom niekto lokálny doladil
- v kóde komponentu použiješ preklad `const m = useMessages();` a `m?.path.to.new.key`

2023-11-05 12:00 UTC, zdila commented
> Prišlo mi to vhodné umiestniť túto fíčuru takto. Príde mi to zbytočné dávať niekde inde ak sa tým menia len objekty.

ak to je zatiaľ lokálne tak OK, lebo podľa tých prvých zmien mi to prišlo že to má byť globálne nastavenie pre všetky markery (čo by raz bolo podľa mňa fajn)

> Čo sa týka zapamätatelnosti, tak všimol som si, že veci ako výber jazyku, či iné záležitosti na mape sú riešené cez localStorage (aspoň sa tak ukladajú), no v kóde som to nenašiel resp. nenašiel som súbor, ktorý to ma nastarosti.

viď. `src/middlewares/statePersistingMiddleware.ts` a `getInitialState` v `src/reducers.ts`.

2023-11-05 12:02 UTC, zdila commented
Nastav si ešte prosím linting a auto formatting do svojho editora, lebo tvoje zmeny pridali nejaké problémy. Viď `npm run lint`.

2023-11-05 12:03 UTC, zdila commented on src/actions/drawingPointActions.ts
> +export const setSelectedIcon = createAction('SET_SELECTED_ICON')<string>();
toto patrí do `src/actions/objectsActions.ts` keďže sa to teraz týka iba funkcie "objekty"

2023-11-05 12:07 UTC, zdila commented on src/components/ToolMenu.tsx
>                </span>
tento súbor nie je nutné meniť a voľbu patria do `src/components/ObjectsMenu.tsx`

2023-11-05 12:08 UTC, zdila commented on src/reducers/mainReducer.ts
> +  })
tento súbor nie je nutné meniť a toto patrí do `src/reducers/objectsReducer.ts`

2023-11-05 12:11 UTC, zdila commented on src/components/RichMarker.tsx
> +export function ObjectMarker({
super že je to v súbore `RichMarker` ale myslel som zaintegrovať priamo do `RichMarker`/`MarkerIcon` komponentu.

2023-11-06 18:32 UTC, robo311 commented
>preklad sa robí takto: 

Ďakujem za nasmerovanie. Implementoval som to do kódu.

> inšpiruj sa prosím dropdownami 

Prerobil som to na Dropdown.

>ring icon má širší okraj ako rectangle icon

Opravené.

> iconAnchor tých nových ikon nesedí 

Celkovo som tie ikony trochu upravil, pretože tam nesedel ten svg viewbox, ale teraz už by to malo byť fajn. 

> viď. src/middlewares/statePersistingMiddleware.ts a getInitialState v src/reducers.ts.

Taktiež ďakujem za nasmerovanie, malo by to už zapamätávať voľbu.

>Nastav si ešte prosím linting a auto formatting do svojho editora, lebo tvoje zmeny pridali nejaké problémy. Viď npm run lint.

Mal som to omylom vypnuté, no už by to malo byť v pohode.

> toto patrí do src/actions/objectsActions.ts keďže sa to teraz týka iba funkcie "objekty"

Vyriešené.

> tento súbor nie je nutné meniť a voľbu patria do src/components/ObjectsMenu.tsx

Vyriešené.

> tento súbor nie je nutné meniť a toto patrí do src/reducers/objectsReducer.ts

Vyriešené.

> super že je to v súbore RichMarker ale myslel som zaintegrovať priamo do RichMarker/MarkerIcon komponentu. 

Nechal som to takto pretože mi to prišlo vhodné spraviť osobitne keďže je to zatiaľ len pre objekty. Potom by sa to mohlo hodiť rovno do RichMarkeru ak to bude pre všetky ikony, nie len pre objekty.

2023-11-07 11:07 UTC, robo311 commented
Zmenil som názov "rectangle" na "square" a trochu upravil preklad.

2023-11-07 22:30 UTC, merged

2023-11-08 11:16 UTC, zdila commented on src/components/RichMarker.tsx
> +export function ObjectMarker({
spravil som to v https://github.com/FreemapSlovakia/freemap-v3-react/commit/7fe519486ab681878da30f61c94e42c77264f688